import { Work_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const workSans = Work_Sans({
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased bg-base-300 text-base-300-content bog-bg`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
